# Generated by Django 3.1.7 on 2021-02-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('V', 'Veg'), ('NV', 'Nonveg')], max_length=2)),
                ('base', models.CharField(choices=[('TC', 'Thin Crust'), ('RB', 'Regular Base'), ('FB', 'Flat Bread'), ('M', 'Multigrain')], max_length=2)),
                ('cheese_type', models.CharField(choices=[('CB', 'Cheese Burst'), ('CT', 'Cheese Topping'), ('NC', 'No Cheese')], max_length=2)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
