# Generated by Django 3.1.7 on 2021-02-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_pizza',
            name='base',
            field=models.CharField(choices=[('Thin Crust', 'Thin Crust'), ('Regular Base', 'Regular Base'), ('Flat Bread', 'Flat Bread'), ('Multigrain', 'Multigrain')], max_length=15),
        ),
        migrations.AlterField(
            model_name='my_pizza',
            name='category',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Nonveg', 'Nonveg')], max_length=10),
        ),
        migrations.AlterField(
            model_name='my_pizza',
            name='cheese_type',
            field=models.CharField(choices=[('Cheese Burst', 'Cheese Burst'), ('Cheese Topping', 'Cheese Topping'), ('No Cheese', 'No Cheese')], max_length=15),
        ),
    ]
