# Generated by Django 3.1.7 on 2021-02-27 02:05

from django.db import migrations, models
import pizza.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20210227_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_pizza',
            name='picture',
            field=models.ImageField(default='pizzas/default.jpeg', upload_to=pizza.models.upload_to, verbose_name='Image'),
        ),
    ]
